"""empty message

Revision ID: 1dc6882a50a0
Revises: dd974cb327de
Create Date: 2025-01-31 17:25:05.457581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc6882a50a0'
down_revision = 'dd974cb327de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group__finances', schema=None) as batch_op:
        batch_op.alter_column('id_group',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group__finances', schema=None) as batch_op:
        batch_op.alter_column('id_group',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
