"""empty message

Revision ID: 5565e0758c29
Revises: 816d86c5c7a8
Create Date: 2025-01-27 20:40:01.889537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5565e0758c29'
down_revision = '816d86c5c7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finances', schema=None) as batch_op:
        batch_op.drop_constraint('finances_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finances', schema=None) as batch_op:
        batch_op.create_unique_constraint('finances_name_key', ['name'])

    # ### end Alembic commands ###
