"""empty message

Revision ID: 816d86c5c7a8
Revises: c36e3781d961
Create Date: 2025-01-27 12:39:24.826737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816d86c5c7a8'
down_revision = 'c36e3781d961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finances', schema=None) as batch_op:
        batch_op.alter_column('id_type',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finances', schema=None) as batch_op:
        batch_op.alter_column('id_type',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
