"""empty message

Revision ID: a45a886a5f06
Revises: 1dc6882a50a0
Create Date: 2025-01-31 17:29:31.654710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45a886a5f06'
down_revision = '1dc6882a50a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_id_group_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_id_group_fkey', 'groups', ['id_group'], ['id_group'])

    # ### end Alembic commands ###
