"""empty message

Revision ID: dd974cb327de
Revises: 5565e0758c29
Create Date: 2025-01-31 17:21:01.949974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd974cb327de'
down_revision = '5565e0758c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_id_group_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_id_group_fkey', 'groups', ['id_group'], ['id_group'], ondelete='SET NULL')

    # ### end Alembic commands ###
